name: 'kafka'
version: 0.1.0
description: Kafka Client library for Dartlang
homepage: https://github.com/ozzpy/dart-kafka
author: Leafar Avlis

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  quiver: ^3.2.1
  logging: ^1.2.0

dev_dependencies:
  test: ^1.24.6
  mockito: ^5.4.2
  dart_coveralls: "^0.4.0"
